### ISSUE TITLE
Latex documenten IIW Brugge

### ISSUE THREAD

**Issue by SofieMartien** [GillesC/KU-Leuven-master-thesis-template-FET#2]
In de Engelstalige LateX-template voor de masterproef is geen Engelstalige variant voor het titelblad (wel beschikbaar voor bv. De Nayer). Daardoor wordt op het titelblad de NL benaming (FIIW) ipv de Engelstalige vermeld (FET). 

Cover_fiiw_brugge.pdf 
Cover_fiiw_denayer_eng.pdf  Not there for Brugge
 

In de Engelstalige template is niet alles vertaald vanuit het NL in de LateX instructies.

**Comment by GillesC** [comment]
Titelblad is toegevoegd in commit 62d1548f0708024997fe7fd8bec289d57998cf4f en meer bijhorence commentaar in 48030ba1fcd3f427bb20033eea4bb3f48e43fe55.
