### ISSUE TITLE
Latex groupt english cover does not work

### ISSUE THREAD

**Issue by moniquepedrososgm23** [GillesC/KU-Leuven-master-thesis-template-FET#3]
I tested the code with both: groept and groupteng as campuses, the first works but the second does not. The following image shows the resulting pdf with groupteng
![image](https://github.com/GillesC/KU-Leuven-master-thesis-template-FET/assets/169714903/5cdd7e6b-598d-487d-91e4-41fe447a3a27)

**Comment by GillesC** [comment]
Thanks for pointing out this bug.  It should work now once you have updated the template with the newest version.
Please confirm by closing the issue.
