### ISSUE TITLE
Problem template brugeseng

### ISSUE THREAD

**Issue by SJon15** [GillesC/KU-Leuven-master-thesis-template-FET#5]
Dear,

If I change my campus code in to brugeseng, my whole frontpage (template voorblad brugge eng) doesn't load.
Is it possible to help me with this problem?

Kind regards,
Jonathan

<img width="1280" alt="Screenshot 2024-12-06 145336" src="https://github.com/user-attachments/assets/272f361a-2bbf-4969-bfcc-0c11f6819dce">

**Comment by GillesC** [comment]
Hi Jonathan,

Indeed, the naming of the cover and front was not correct for campus Bruges. I have update the naming in the latest push.
You can do two things:
- rename ‎`covers/back_fiiw_brugge_eng.pdf`  ‎-> `covers/back_fiiw_bruges_eng.pdf` and ‎`covers/cover_fiiw_brugge_eng.pdf`  -> ‎`covers/cover_fiiw_bruges_eng.pdf` or
- pull the latest version from this Github (or just the files in the ‎`covers` folder).

**Comment by SJon15** [comment]
Thank you very much!!
